baseURL = 'https://toto1010orange.github.io/legal-blog/'
languageCode = 'ja-jp'
title = '情報学生法学記'
defaultContentLanguage="ja"
theme = "PaperMod"
[params]
  author = "toto1010orange"
  ShowToc=true
  TocOpen= false
  ShowReadingTime =true
  ShowShareButtons=true
  ShowPostNavLinks=true
